### ISSUE TITLE
빌리기 요청 / 취소 기능 구현

### ISSUE THREAD

**Issue by jbsquee** [bong-dragon/cowlib#24]
- [x] 주인이 아닌 경우 확인하기
- [x] 대기자 보여주지 않고 -> 대기자 수만 보여주기
- [x] 예약버튼 / 취소버튼 보여주기
- [ ] 예약 / 취소 버튼 기능 구현

**Comment by dragonist** [comment]
- action에 연결 시키기
- reducer 동작하게 하기
